task: detection

__include__: ["../runtime.yml", "../include/optimizer.yml"]
output_dir: /home/prml/StudentsWork/Chanyoung/dexter/result/tiny
epoches: 72

# ======================== Dataset Config ======================== #
num_classes: 80
remap_mscoco_category: True

train_dataloader:
  type: DataLoader
  dataset:
    type: CocoDetection
    img_folder: /home/prml/Dataset/coco2017/train2017/
    ann_file: /home/prml/Dataset/coco2017/annotations/instances_train2017.json
    transforms:
      type: Compose
      ops:
        - { type: RandomPhotometricDistort, p: 0.5 }
        - { type: RandomZoomOut, fill: 0 }
        - { type: RandomIoUCrop, p: 0.8 }
        - { type: SanitizeBoundingBoxes, min_size: 1 }
        - { type: RandomHorizontalFlip }
        - { type: Resize, size: [640, 640] }
        - { type: ToImage }
        - { type: ConvertImageDtype }
        - { type: SanitizeBoundingBoxes, min_size: 1 }
        - { type: ConvertBox, out_fmt: "cxcywh", normalize: True }
  shuffle: True
  batch_size: 8
  num_workers: 8
  drop_last: True
  collate_fn: default_collate_fn

val_dataloader:
  type: DataLoader
  dataset:
    type: CocoDetection
    img_folder: /home/prml/Dataset/coco2017/val2017/
    ann_file: /home/prml/Dataset/coco2017/annotations/instances_val2017.json
    transforms:
      type: Compose
      ops:
        - { type: Resize, size: [640, 640] }
        - { type: ToImage }
        - { type: ConvertImageDtype }

  shuffle: False
  batch_size: 8
  num_workers: 8
  collate_fn: default_collate_fn
  drop_last: False

# ======================== Model Config ======================== #
model: Dexter
criterion: DETRCriterion
postprocessor: DETRPostProcessor

Dexter:
  backbone: ConvNeXtV2
  encoder: DexterEncoder
  decoder: DexterDecoder
  multi_scale: [640]

ConvNeXtV2:
  model_size: "tiny"
  return_idx: [0, 1, 2, 3]
  pretrained: True
  freeze_at: -1

DexterEncoder:
  in_channels: [96, 192, 384, 768]
  feat_strides: [4, 8, 16, 32]

  # intra
  dim: 192
  start_idx: 1
  use_encoder_idx: [3]
  num_encoder_layers: 1
  nhead: 8
  dim_feedforward: 768
  dropout: 0.
  enc_act: "gelu"
  pe_temperature: 10000

  # cross
  expansion: 1.0
  depth_mult: 1.0
  act: "gelu"

  # eval
  eval_spatial_size: [640, 640]

DexterDecoder:
  feat_channels: [192, 192, 192, 192]
  feat_strides: [4, 8, 16, 32]
  dim: 256
  num_levels: 4
  query_select_start_levels: 1

  num_queries: 300

  num_decoder_layers: 6
  num_drop_queries: [25, 25, 25, 25, 25, 25]
  num_denoising: 100

  eval_idx: -1
  eval_spatial_size: [640, 640]

  query_decomp: True
  attn_redoer: True

use_focal_loss: True

DETRPostProcessor:
  num_top_queries: 150

DETRCriterion:
  weight_dict: { loss_vfl: 1, loss_bbox: 5, loss_giou: 2 }
  losses: ["vfl", "boxes"]
  alpha: 0.75
  gamma: 2.0

  matcher:
    type: HungarianMatcher
    weight_dict: { cost_class: 2, cost_bbox: 5, cost_giou: 2 }
    # use_focal_loss: True
    alpha: 0.25
    gamma: 2.0
